// Code generated by ent, DO NOT EDIT.

package team

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTeam holds the string denoting the team field in the database.
	FieldTeam = "team"
	// FieldMitarbeiter holds the string denoting the mitarbeiter field in the database.
	FieldMitarbeiter = "mitarbeiter"
	// FieldFarbe holds the string denoting the farbe field in the database.
	FieldFarbe = "farbe"
	// FieldOrt holds the string denoting the ort field in the database.
	FieldOrt = "ort"
	// EdgeTeamName holds the string denoting the teamname edge name in mutations.
	EdgeTeamName = "teamName"
	// EdgeJahr holds the string denoting the jahr edge name in mutations.
	EdgeJahr = "Jahr"
	// Table holds the table name of the team in the database.
	Table = "teams"
	// TeamNameTable is the table that holds the teamName relation/edge.
	TeamNameTable = "artikels"
	// TeamNameInverseTable is the table name for the Artikel entity.
	// It exists in this package in order to avoid circular dependency with the "artikel" package.
	TeamNameInverseTable = "artikels"
	// TeamNameColumn is the table column denoting the teamName relation/edge.
	TeamNameColumn = "team_team_name"
	// JahrTable is the table that holds the Jahr relation/edge.
	JahrTable = "teams"
	// JahrInverseTable is the table name for the Inventur entity.
	// It exists in this package in order to avoid circular dependency with the "inventur" package.
	JahrInverseTable = "inventurs"
	// JahrColumn is the table column denoting the Jahr relation/edge.
	JahrColumn = "inventur_teams"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldTeam,
	FieldMitarbeiter,
	FieldFarbe,
	FieldOrt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "teams"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"inventur_teams",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Team queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTeam orders the results by the Team field.
func ByTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTeam, opts...).ToFunc()
}

// ByMitarbeiter orders the results by the Mitarbeiter field.
func ByMitarbeiter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMitarbeiter, opts...).ToFunc()
}

// ByFarbe orders the results by the Farbe field.
func ByFarbe(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFarbe, opts...).ToFunc()
}

// ByOrt orders the results by the Ort field.
func ByOrt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrt, opts...).ToFunc()
}

// ByTeamNameCount orders the results by teamName count.
func ByTeamNameCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamNameStep(), opts...)
	}
}

// ByTeamName orders the results by teamName terms.
func ByTeamName(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamNameStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByJahrField orders the results by Jahr field.
func ByJahrField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newJahrStep(), sql.OrderByField(field, opts...))
	}
}
func newTeamNameStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamNameInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeamNameTable, TeamNameColumn),
	)
}
func newJahrStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(JahrInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, JahrTable, JahrColumn),
	)
}
