// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnsprechpartnersColumns holds the columns for the "ansprechpartners" table.
	AnsprechpartnersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "telefon", Type: field.TypeString, Nullable: true},
		{Name: "mobil", Type: field.TypeString, Nullable: true},
		{Name: "mail", Type: field.TypeString, Nullable: true},
		{Name: "lieferant_ansprechpartner", Type: field.TypeInt, Nullable: true},
	}
	// AnsprechpartnersTable holds the schema information for the "ansprechpartners" table.
	AnsprechpartnersTable = &schema.Table{
		Name:       "ansprechpartners",
		Columns:    AnsprechpartnersColumns,
		PrimaryKey: []*schema.Column{AnsprechpartnersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ansprechpartners_lieferants_Ansprechpartner",
				Columns:    []*schema.Column{AnsprechpartnersColumns[5]},
				RefColumns: []*schema.Column{LieferantsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ArtikelsColumns holds the columns for the "artikels" table.
	ArtikelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "artikelnummer", Type: field.TypeString},
		{Name: "suchbegriff", Type: field.TypeString},
		{Name: "anzahl", Type: field.TypeInt},
		{Name: "team_artikel", Type: field.TypeInt, Nullable: true},
	}
	// ArtikelsTable holds the schema information for the "artikels" table.
	ArtikelsTable = &schema.Table{
		Name:       "artikels",
		Columns:    ArtikelsColumns,
		PrimaryKey: []*schema.Column{ArtikelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artikels_teams_artikel",
				Columns:    []*schema.Column{ArtikelsColumns[4]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// InventursColumns holds the columns for the "inventurs" table.
	InventursColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "jahr", Type: field.TypeInt, Unique: true},
	}
	// InventursTable holds the schema information for the "inventurs" table.
	InventursTable = &schema.Table{
		Name:       "inventurs",
		Columns:    InventursColumns,
		PrimaryKey: []*schema.Column{InventursColumns[0]},
	}
	// LieferantsColumns holds the columns for the "lieferants" table.
	LieferantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "firma", Type: field.TypeString, Unique: true},
		{Name: "kundennummer", Type: field.TypeString, Nullable: true},
		{Name: "webseite", Type: field.TypeString, Nullable: true},
	}
	// LieferantsTable holds the schema information for the "lieferants" table.
	LieferantsTable = &schema.Table{
		Name:       "lieferants",
		Columns:    LieferantsColumns,
		PrimaryKey: []*schema.Column{LieferantsColumns[0]},
	}
	// MitarbeitersColumns holds the columns for the "mitarbeiters" table.
	MitarbeitersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "short", Type: field.TypeString, Nullable: true},
		{Name: "gruppenwahl", Type: field.TypeString, Nullable: true},
		{Name: "intern_telefon1", Type: field.TypeString, Nullable: true},
		{Name: "intern_telefon2", Type: field.TypeString, Nullable: true},
		{Name: "festnetz_privat", Type: field.TypeString, Nullable: true},
		{Name: "festnetz_alternativ", Type: field.TypeString, Nullable: true},
		{Name: "home_office", Type: field.TypeString, Nullable: true},
		{Name: "mobil_business", Type: field.TypeString, Nullable: true},
		{Name: "mobil_privat", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "azubi", Type: field.TypeBool, Default: false},
		{Name: "geburtstag", Type: field.TypeTime, Nullable: true},
		{Name: "paypal", Type: field.TypeBool, Default: false},
		{Name: "abonniert", Type: field.TypeBool, Default: false},
		{Name: "geld", Type: field.TypeString, Nullable: true},
		{Name: "pfand", Type: field.TypeString, Nullable: true},
		{Name: "dinge", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "abgeschickt", Type: field.TypeTime, Nullable: true},
		{Name: "bild1", Type: field.TypeString, Nullable: true},
		{Name: "bild2", Type: field.TypeString, Nullable: true},
		{Name: "bild3", Type: field.TypeString, Nullable: true},
		{Name: "bild1date", Type: field.TypeTime, Nullable: true},
		{Name: "bild2date", Type: field.TypeTime, Nullable: true},
		{Name: "bild3date", Type: field.TypeTime, Nullable: true},
		{Name: "user_mitarbeiter", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// MitarbeitersTable holds the schema information for the "mitarbeiters" table.
	MitarbeitersTable = &schema.Table{
		Name:       "mitarbeiters",
		Columns:    MitarbeitersColumns,
		PrimaryKey: []*schema.Column{MitarbeitersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mitarbeiters_users_mitarbeiter",
				Columns:    []*schema.Column{MitarbeitersColumns[26]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "team", Type: field.TypeInt, Unique: true},
		{Name: "mitarbeiter", Type: field.TypeString},
		{Name: "farbe", Type: field.TypeString},
		{Name: "ort", Type: field.TypeString},
		{Name: "inventur_teams", Type: field.TypeInt, Nullable: true},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "teams_inventurs_Teams",
				Columns:    []*schema.Column{TeamsColumns[5]},
				RefColumns: []*schema.Column{InventursColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "mail", Type: field.TypeString, Unique: true},
		{Name: "active", Type: field.TypeBool, Default: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VersionsColumns holds the columns for the "versions" table.
	VersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "current_version", Type: field.TypeFloat64, Unique: true},
	}
	// VersionsTable holds the schema information for the "versions" table.
	VersionsTable = &schema.Table{
		Name:       "versions",
		Columns:    VersionsColumns,
		PrimaryKey: []*schema.Column{VersionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnsprechpartnersTable,
		ArtikelsTable,
		InventursTable,
		LieferantsTable,
		MitarbeitersTable,
		TeamsTable,
		UsersTable,
		VersionsTable,
	}
)

func init() {
	AnsprechpartnersTable.ForeignKeys[0].RefTable = LieferantsTable
	ArtikelsTable.ForeignKeys[0].RefTable = TeamsTable
	MitarbeitersTable.ForeignKeys[0].RefTable = UsersTable
	TeamsTable.ForeignKeys[0].RefTable = InventursTable
}
