// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-backend/ent/inventur"
	"golang-backend/ent/team"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InventurCreate is the builder for creating a Inventur entity.
type InventurCreate struct {
	config
	mutation *InventurMutation
	hooks    []Hook
}

// SetJahr sets the "Jahr" field.
func (ic *InventurCreate) SetJahr(i int) *InventurCreate {
	ic.mutation.SetJahr(i)
	return ic
}

// AddTeamIDs adds the "Teams" edge to the Team entity by IDs.
func (ic *InventurCreate) AddTeamIDs(ids ...int) *InventurCreate {
	ic.mutation.AddTeamIDs(ids...)
	return ic
}

// AddTeams adds the "Teams" edges to the Team entity.
func (ic *InventurCreate) AddTeams(t ...*Team) *InventurCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ic.AddTeamIDs(ids...)
}

// Mutation returns the InventurMutation object of the builder.
func (ic *InventurCreate) Mutation() *InventurMutation {
	return ic.mutation
}

// Save creates the Inventur in the database.
func (ic *InventurCreate) Save(ctx context.Context) (*Inventur, error) {
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InventurCreate) SaveX(ctx context.Context) *Inventur {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InventurCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InventurCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InventurCreate) check() error {
	if _, ok := ic.mutation.Jahr(); !ok {
		return &ValidationError{Name: "Jahr", err: errors.New(`ent: missing required field "Inventur.Jahr"`)}
	}
	return nil
}

func (ic *InventurCreate) sqlSave(ctx context.Context) (*Inventur, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InventurCreate) createSpec() (*Inventur, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventur{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(inventur.Table, sqlgraph.NewFieldSpec(inventur.FieldID, field.TypeInt))
	)
	if value, ok := ic.mutation.Jahr(); ok {
		_spec.SetField(inventur.FieldJahr, field.TypeInt, value)
		_node.Jahr = value
	}
	if nodes := ic.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventur.TeamsTable,
			Columns: []string{inventur.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InventurCreateBulk is the builder for creating many Inventur entities in bulk.
type InventurCreateBulk struct {
	config
	err      error
	builders []*InventurCreate
}

// Save creates the Inventur entities in the database.
func (icb *InventurCreateBulk) Save(ctx context.Context) ([]*Inventur, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Inventur, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventurMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InventurCreateBulk) SaveX(ctx context.Context) []*Inventur {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InventurCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InventurCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
