// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-backend/ent/inventur"
	"golang-backend/ent/team"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InventurCreate is the builder for creating a Inventur entity.
type InventurCreate struct {
	config
	mutation *InventurMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJahr sets the "Jahr" field.
func (ic *InventurCreate) SetJahr(i int) *InventurCreate {
	ic.mutation.SetJahr(i)
	return ic
}

// AddTeamIDs adds the "Teams" edge to the Team entity by IDs.
func (ic *InventurCreate) AddTeamIDs(ids ...int) *InventurCreate {
	ic.mutation.AddTeamIDs(ids...)
	return ic
}

// AddTeams adds the "Teams" edges to the Team entity.
func (ic *InventurCreate) AddTeams(t ...*Team) *InventurCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ic.AddTeamIDs(ids...)
}

// Mutation returns the InventurMutation object of the builder.
func (ic *InventurCreate) Mutation() *InventurMutation {
	return ic.mutation
}

// Save creates the Inventur in the database.
func (ic *InventurCreate) Save(ctx context.Context) (*Inventur, error) {
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InventurCreate) SaveX(ctx context.Context) *Inventur {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InventurCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InventurCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InventurCreate) check() error {
	if _, ok := ic.mutation.Jahr(); !ok {
		return &ValidationError{Name: "Jahr", err: errors.New(`ent: missing required field "Inventur.Jahr"`)}
	}
	return nil
}

func (ic *InventurCreate) sqlSave(ctx context.Context) (*Inventur, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InventurCreate) createSpec() (*Inventur, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventur{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(inventur.Table, sqlgraph.NewFieldSpec(inventur.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ic.conflict
	if value, ok := ic.mutation.Jahr(); ok {
		_spec.SetField(inventur.FieldJahr, field.TypeInt, value)
		_node.Jahr = value
	}
	if nodes := ic.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventur.TeamsTable,
			Columns: []string{inventur.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inventur.Create().
//		SetJahr(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventurUpsert) {
//			SetJahr(v+v).
//		}).
//		Exec(ctx)
func (ic *InventurCreate) OnConflict(opts ...sql.ConflictOption) *InventurUpsertOne {
	ic.conflict = opts
	return &InventurUpsertOne{
		create: ic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inventur.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ic *InventurCreate) OnConflictColumns(columns ...string) *InventurUpsertOne {
	ic.conflict = append(ic.conflict, sql.ConflictColumns(columns...))
	return &InventurUpsertOne{
		create: ic,
	}
}

type (
	// InventurUpsertOne is the builder for "upsert"-ing
	//  one Inventur node.
	InventurUpsertOne struct {
		create *InventurCreate
	}

	// InventurUpsert is the "OnConflict" setter.
	InventurUpsert struct {
		*sql.UpdateSet
	}
)

// SetJahr sets the "Jahr" field.
func (u *InventurUpsert) SetJahr(v int) *InventurUpsert {
	u.Set(inventur.FieldJahr, v)
	return u
}

// UpdateJahr sets the "Jahr" field to the value that was provided on create.
func (u *InventurUpsert) UpdateJahr() *InventurUpsert {
	u.SetExcluded(inventur.FieldJahr)
	return u
}

// AddJahr adds v to the "Jahr" field.
func (u *InventurUpsert) AddJahr(v int) *InventurUpsert {
	u.Add(inventur.FieldJahr, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Inventur.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InventurUpsertOne) UpdateNewValues() *InventurUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inventur.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventurUpsertOne) Ignore() *InventurUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventurUpsertOne) DoNothing() *InventurUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventurCreate.OnConflict
// documentation for more info.
func (u *InventurUpsertOne) Update(set func(*InventurUpsert)) *InventurUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventurUpsert{UpdateSet: update})
	}))
	return u
}

// SetJahr sets the "Jahr" field.
func (u *InventurUpsertOne) SetJahr(v int) *InventurUpsertOne {
	return u.Update(func(s *InventurUpsert) {
		s.SetJahr(v)
	})
}

// AddJahr adds v to the "Jahr" field.
func (u *InventurUpsertOne) AddJahr(v int) *InventurUpsertOne {
	return u.Update(func(s *InventurUpsert) {
		s.AddJahr(v)
	})
}

// UpdateJahr sets the "Jahr" field to the value that was provided on create.
func (u *InventurUpsertOne) UpdateJahr() *InventurUpsertOne {
	return u.Update(func(s *InventurUpsert) {
		s.UpdateJahr()
	})
}

// Exec executes the query.
func (u *InventurUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventurCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventurUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventurUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventurUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventurCreateBulk is the builder for creating many Inventur entities in bulk.
type InventurCreateBulk struct {
	config
	err      error
	builders []*InventurCreate
	conflict []sql.ConflictOption
}

// Save creates the Inventur entities in the database.
func (icb *InventurCreateBulk) Save(ctx context.Context) ([]*Inventur, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Inventur, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventurMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = icb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InventurCreateBulk) SaveX(ctx context.Context) []*Inventur {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InventurCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InventurCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Inventur.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventurUpsert) {
//			SetJahr(v+v).
//		}).
//		Exec(ctx)
func (icb *InventurCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventurUpsertBulk {
	icb.conflict = opts
	return &InventurUpsertBulk{
		create: icb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Inventur.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (icb *InventurCreateBulk) OnConflictColumns(columns ...string) *InventurUpsertBulk {
	icb.conflict = append(icb.conflict, sql.ConflictColumns(columns...))
	return &InventurUpsertBulk{
		create: icb,
	}
}

// InventurUpsertBulk is the builder for "upsert"-ing
// a bulk of Inventur nodes.
type InventurUpsertBulk struct {
	create *InventurCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Inventur.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InventurUpsertBulk) UpdateNewValues() *InventurUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Inventur.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventurUpsertBulk) Ignore() *InventurUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventurUpsertBulk) DoNothing() *InventurUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventurCreateBulk.OnConflict
// documentation for more info.
func (u *InventurUpsertBulk) Update(set func(*InventurUpsert)) *InventurUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventurUpsert{UpdateSet: update})
	}))
	return u
}

// SetJahr sets the "Jahr" field.
func (u *InventurUpsertBulk) SetJahr(v int) *InventurUpsertBulk {
	return u.Update(func(s *InventurUpsert) {
		s.SetJahr(v)
	})
}

// AddJahr adds v to the "Jahr" field.
func (u *InventurUpsertBulk) AddJahr(v int) *InventurUpsertBulk {
	return u.Update(func(s *InventurUpsert) {
		s.AddJahr(v)
	})
}

// UpdateJahr sets the "Jahr" field to the value that was provided on create.
func (u *InventurUpsertBulk) UpdateJahr() *InventurUpsertBulk {
	return u.Update(func(s *InventurUpsert) {
		s.UpdateJahr()
	})
}

// Exec executes the query.
func (u *InventurUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventurCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventurCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventurUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
