// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-backend/ent/artikel"
	"golang-backend/ent/inventur"
	"golang-backend/ent/team"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamCreate is the builder for creating a Team entity.
type TeamCreate struct {
	config
	mutation *TeamMutation
	hooks    []Hook
}

// SetTeam sets the "Team" field.
func (tc *TeamCreate) SetTeam(i int) *TeamCreate {
	tc.mutation.SetTeam(i)
	return tc
}

// SetMitarbeiter sets the "Mitarbeiter" field.
func (tc *TeamCreate) SetMitarbeiter(s string) *TeamCreate {
	tc.mutation.SetMitarbeiter(s)
	return tc
}

// SetFarbe sets the "Farbe" field.
func (tc *TeamCreate) SetFarbe(s string) *TeamCreate {
	tc.mutation.SetFarbe(s)
	return tc
}

// SetOrt sets the "Ort" field.
func (tc *TeamCreate) SetOrt(s string) *TeamCreate {
	tc.mutation.SetOrt(s)
	return tc
}

// AddTeamNameIDs adds the "teamName" edge to the Artikel entity by IDs.
func (tc *TeamCreate) AddTeamNameIDs(ids ...int) *TeamCreate {
	tc.mutation.AddTeamNameIDs(ids...)
	return tc
}

// AddTeamName adds the "teamName" edges to the Artikel entity.
func (tc *TeamCreate) AddTeamName(a ...*Artikel) *TeamCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tc.AddTeamNameIDs(ids...)
}

// SetJahrID sets the "Jahr" edge to the Inventur entity by ID.
func (tc *TeamCreate) SetJahrID(id int) *TeamCreate {
	tc.mutation.SetJahrID(id)
	return tc
}

// SetNillableJahrID sets the "Jahr" edge to the Inventur entity by ID if the given value is not nil.
func (tc *TeamCreate) SetNillableJahrID(id *int) *TeamCreate {
	if id != nil {
		tc = tc.SetJahrID(*id)
	}
	return tc
}

// SetJahr sets the "Jahr" edge to the Inventur entity.
func (tc *TeamCreate) SetJahr(i *Inventur) *TeamCreate {
	return tc.SetJahrID(i.ID)
}

// Mutation returns the TeamMutation object of the builder.
func (tc *TeamCreate) Mutation() *TeamMutation {
	return tc.mutation
}

// Save creates the Team in the database.
func (tc *TeamCreate) Save(ctx context.Context) (*Team, error) {
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TeamCreate) SaveX(ctx context.Context) *Team {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TeamCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TeamCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TeamCreate) check() error {
	if _, ok := tc.mutation.Team(); !ok {
		return &ValidationError{Name: "Team", err: errors.New(`ent: missing required field "Team.Team"`)}
	}
	if _, ok := tc.mutation.Mitarbeiter(); !ok {
		return &ValidationError{Name: "Mitarbeiter", err: errors.New(`ent: missing required field "Team.Mitarbeiter"`)}
	}
	if _, ok := tc.mutation.Farbe(); !ok {
		return &ValidationError{Name: "Farbe", err: errors.New(`ent: missing required field "Team.Farbe"`)}
	}
	if _, ok := tc.mutation.Ort(); !ok {
		return &ValidationError{Name: "Ort", err: errors.New(`ent: missing required field "Team.Ort"`)}
	}
	return nil
}

func (tc *TeamCreate) sqlSave(ctx context.Context) (*Team, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TeamCreate) createSpec() (*Team, *sqlgraph.CreateSpec) {
	var (
		_node = &Team{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(team.Table, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Team(); ok {
		_spec.SetField(team.FieldTeam, field.TypeInt, value)
		_node.Team = value
	}
	if value, ok := tc.mutation.Mitarbeiter(); ok {
		_spec.SetField(team.FieldMitarbeiter, field.TypeString, value)
		_node.Mitarbeiter = value
	}
	if value, ok := tc.mutation.Farbe(); ok {
		_spec.SetField(team.FieldFarbe, field.TypeString, value)
		_node.Farbe = value
	}
	if value, ok := tc.mutation.Ort(); ok {
		_spec.SetField(team.FieldOrt, field.TypeString, value)
		_node.Ort = value
	}
	if nodes := tc.mutation.TeamNameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.TeamNameTable,
			Columns: []string{team.TeamNameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artikel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.JahrIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.JahrTable,
			Columns: []string{team.JahrColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventur.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.inventur_teams = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamCreateBulk is the builder for creating many Team entities in bulk.
type TeamCreateBulk struct {
	config
	err      error
	builders []*TeamCreate
}

// Save creates the Team entities in the database.
func (tcb *TeamCreateBulk) Save(ctx context.Context) ([]*Team, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Team, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TeamCreateBulk) SaveX(ctx context.Context) []*Team {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TeamCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TeamCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
