// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function GetAllMitarbeiter():Promise<Array<db.MitarbeiterModel>>;

export function Greet(arg1:string):Promise<string>;
