// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ent} from '../models';

export function ActivateUser(arg1:number):Promise<boolean>;

export function ChangePassword(arg1:number,arg2:string,arg3:string):Promise<boolean>;

export function CreateUser(arg1:main.UserParams):Promise<boolean>;

export function DeactivateUser(arg1:number):Promise<boolean>;

export function DeleteAnsprechpartner(arg1:number):Promise<boolean>;

export function DeleteEinkauf(arg1:number):Promise<boolean>;

export function DeleteLieferant(arg1:number):Promise<boolean>;

export function DeleteMitarbeiter(arg1:number):Promise<boolean>;

export function GetAllMitarbeiter():Promise<Array<ent.Mitarbeiter>>;

export function GetAllMitarbeiterWithoutMail():Promise<Array<ent.Mitarbeiter>>;

export function GetAnsprechpartner(arg1:number):Promise<ent.Ansprechpartner>;

export function GetArchive(arg1:string):Promise<string>;

export function GetDataFromYear(arg1:number):Promise<Array<ent.Team>>;

export function GetEinkauf(arg1:number):Promise<ent.Mitarbeiter>;

export function GetEinkaufsListe():Promise<Array<main.Einkauf>>;

export function GetEntriesFromTeam(arg1:number):Promise<Array<ent.Artikel>>;

export function GetGeburtstagsListe():Promise<main.GeburtstagList>;

export function GetInventurYears():Promise<Array<ent.Inventur>>;

export function GetKunde(arg1:string):Promise<main.User>;

export function GetLieferant(arg1:number):Promise<main.Lieferant>;

export function GetLieferanten():Promise<Array<main.Lieferant>>;

export function GetMitarbeiter(arg1:number):Promise<ent.Mitarbeiter>;

export function GetMitarbeiterIdByName(arg1:string):Promise<number>;

export function GetUser(arg1:number):Promise<ent.User>;

export function GetUsername():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<main.UserWithMa>;

export function SearchArchive(arg1:string):Promise<Array<main.Archive>>;

export function SearchSage(arg1:string):Promise<Array<main.Sg_Adressen>>;

export function SendAbrechnung(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SkipEinkauf(arg1:number):Promise<boolean>;

export function UpdateEinkauf(arg1:main.UpsertEinkaufParams,arg2:number):Promise<boolean>;

export function UploadImage(arg1:number,arg2:string):Promise<string>;

export function UpsertAnsprechpartner(arg1:main.AnsprechpartnerParams):Promise<boolean>;

export function UpsertLieferant(arg1:main.LieferantenParams):Promise<boolean>;

export function UpsertMitarbeiter(arg1:main.MitarbeiterParams):Promise<boolean>;
