// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckImage(arg1, arg2) {
  return window['go']['main']['App']['CheckImage'](arg1, arg2);
}

export function DeleteAnsprechpartner(arg1) {
  return window['go']['main']['App']['DeleteAnsprechpartner'](arg1);
}

export function DeleteEinkauf(arg1) {
  return window['go']['main']['App']['DeleteEinkauf'](arg1);
}

export function DeleteLieferant(arg1) {
  return window['go']['main']['App']['DeleteLieferant'](arg1);
}

export function DeleteMitarbeiter(arg1) {
  return window['go']['main']['App']['DeleteMitarbeiter'](arg1);
}

export function GetAllMitarbeiter() {
  return window['go']['main']['App']['GetAllMitarbeiter']();
}

export function GetAnsprechpartner(arg1) {
  return window['go']['main']['App']['GetAnsprechpartner'](arg1);
}

export function GetArchive(arg1) {
  return window['go']['main']['App']['GetArchive'](arg1);
}

export function GetDataFromYear(arg1) {
  return window['go']['main']['App']['GetDataFromYear'](arg1);
}

export function GetEinkauf(arg1) {
  return window['go']['main']['App']['GetEinkauf'](arg1);
}

export function GetEinkaufsListe() {
  return window['go']['main']['App']['GetEinkaufsListe']();
}

export function GetEntriesFromTeam(arg1) {
  return window['go']['main']['App']['GetEntriesFromTeam'](arg1);
}

export function GetInventurYears() {
  return window['go']['main']['App']['GetInventurYears']();
}

export function GetKunde(arg1) {
  return window['go']['main']['App']['GetKunde'](arg1);
}

export function GetLieferant(arg1) {
  return window['go']['main']['App']['GetLieferant'](arg1);
}

export function GetLieferanten() {
  return window['go']['main']['App']['GetLieferanten']();
}

export function GetMitarbeiter(arg1) {
  return window['go']['main']['App']['GetMitarbeiter'](arg1);
}

export function GetMitarbeiterIdByName(arg1) {
  return window['go']['main']['App']['GetMitarbeiterIdByName'](arg1);
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function SearchArchive(arg1) {
  return window['go']['main']['App']['SearchArchive'](arg1);
}

export function SearchSage(arg1) {
  return window['go']['main']['App']['SearchSage'](arg1);
}

export function SendAbrechnung(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAbrechnung'](arg1, arg2, arg3);
}

export function SkipEinkauf(arg1) {
  return window['go']['main']['App']['SkipEinkauf'](arg1);
}

export function UpdateEinkauf(arg1, arg2) {
  return window['go']['main']['App']['UpdateEinkauf'](arg1, arg2);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}

export function UpsertAnsprechpartner(arg1) {
  return window['go']['main']['App']['UpsertAnsprechpartner'](arg1);
}

export function UpsertLieferant(arg1) {
  return window['go']['main']['App']['UpsertLieferant'](arg1);
}

export function UpsertMitarbeiter(arg1) {
  return window['go']['main']['App']['UpsertMitarbeiter'](arg1);
}
