// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ansprechpartner is the predicate function for ansprechpartner builders.
type Ansprechpartner func(*sql.Selector)

// Artikel is the predicate function for artikel builders.
type Artikel func(*sql.Selector)

// Inventur is the predicate function for inventur builders.
type Inventur func(*sql.Selector)

// Lieferant is the predicate function for lieferant builders.
type Lieferant func(*sql.Selector)

// Mitarbeiter is the predicate function for mitarbeiter builders.
type Mitarbeiter func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)
